### ISSUE TITLE
Invalid Requirements.txt

### ISSUE THREAD

**Issue by Jallen3893** [alex-suspicious/OctoTex#9]
Line 7 of Requirements.txt is invalid. The whole file should look like this:

tqdm
pillow
numpy
scipy
matplotlib
wand
torch --index-url https://download.pytorch.org/whl/cu118
torchvision --index-url https://download.pytorch.org/whl/cu118
torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by alex-suspicious** [comment]
Thanks!
